use std::fs::File;
use std::path::PathBuf;

use homestat_build::Cyw43439Regions;

/// Linker file entry to cortex-m-rt
///
/// MUST be called "memory.x".
/// https://docs.rs/cortex-m-rt/latest/cortex_m_rt/#memoryx
const MAIN_LINKER_FILE: &str = "memory.x";

/// Must be kept in sync in memory.x
const GENERATED_LINKER_FILE: &str = "homestat.x";

/// Generated by xtask FlashFirmware
const FIRMWARE_FLASH_METADATA: &str = concat!(
    env!("CARGO_WORKSPACE_DIR"),
    "/misc/firmware/flash-metadata.json"
);

fn main() {
    let cargo_out = &PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    println!("cargo:rustc-link-search={}", cargo_out.display());

    // load firmware flash metadata
    let metadata_file = File::open(FIRMWARE_FLASH_METADATA).unwrap();
    let cyw = Cyw43439Regions::read_json(metadata_file).unwrap();

    // write generated linker file
    let mut generated_linker_file = File::create(cargo_out.join(GENERATED_LINKER_FILE)).unwrap();
    cyw.write_linker(&mut generated_linker_file).unwrap();
    println!("cargo:rerun-if-changed={}", FIRMWARE_FLASH_METADATA);

    // write main linker file
    std::fs::copy(MAIN_LINKER_FILE, cargo_out.join(MAIN_LINKER_FILE)).unwrap();
    println!("cargo:rerun-if-changed={}", MAIN_LINKER_FILE);

    // lld: "--nmagic, -n Do not page align sections, link against static libraries."
    println!("cargo:rustc-link-arg-bins=--nmagic");

    // add dependency linker files
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tlink-rp.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
}
