[package]
name = "homestat-build"
version = "0.1.0"
edition = "2024"

[features]
default = ["full"]
full = ["dep:hex", "dep:serde", "dep:serde_json"]
reflect = ["dep:reflect-instantiate"]

[dependencies]
reflect-instantiate = { path = "../reflect-instantiate", optional = true }

hex = { version = "0.4.3", features = ["serde"], optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
serde_json = { version = "1.0.145", optional = true }
