[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "cargo-flash --chip RP2040"
# install from https://github.com/raspberrypi/pico-sdk-tools/releases
runner = "picotool load --update --verify --execute -t elf"

[env]
DEFMT_LOG = "debug"
